### ISSUE TITLE
FEAT : 시음 노트 도메인 설계 및 개발

### ISSUE THREAD

**Issue by jinyngg** [juulabel/juulabel-back#26]
### TO-DO

시음노트 도메인 설계 진행

## 👨‍💻 기능
구현 기능을 작성한다. (ex. 게시글 작성 기능 구현)
- [x] 도메인 생성
- [x] 전통주 조회 
- [x] 시각 정보 조회
- [x] 촉각 정보 조회
- [x] 후각 정보 조회
- [x] 미각 정보 조회
- [ ] 시음 노트 작성 (주관 평가 진행)
- [ ] 테스트 코드 작성

## 📖 참고
참고사항을 작성한다. (ex. 게시글 삭제 리팩토링 필요)
